### ISSUE TITLE
As a baseball fan, I want to see the stadiums and its team name that has the smallest distance to center field.

### ISSUE THREAD

**Issue by Alankvuong** [gomihiko/BaseballTour#23]
DESCRIPTION:
a. A baseball fan would be able to see which stadium and its corresponding team has the least distance to the center of the field.

TASKS:
a. Create a method to find the least distance in each stadium.
b. Create a window/scroll window that can show the stadium and team after the baseball fan selects this option.

TESTS:
a. Pull information from the database to obtain the distance of each stadium to the center field to see if the least distance is shown in the window.

ESTIMATION:

ASSUMPTIONS:
a. The database is set up and ready to be queried.
b. The baseball fan has the option to select this option from a menu.

PRIORITY:

DONE:
a. The baseball fan is visibly able to see which stadium has the least distance to the center field.

**Comment by gomihiko** [comment]
Make sure to change "user" to "baseball fan" in this story so we receive full credit for it.
